### PR TITLE
fix aria-owns calculation

### LINKED ISSUE #19: fix aria-owns calculation
As per F2F, there's something rotten in the state of aria-owns.

### PR DESCRIPTION
**Pull request by pkra**
Fixes #19.

### CODE REVIEW

File: navigator.mjs [hunk 1]
```diff
@@ -1,81 +1,12 @@
-import {makeid} from './helpers.mjs'
+import {makeTree, tree} from './tree.mjs';
```
Comment (pkra) [inline navigator.mjs]: This is no longer needed - nice!

**Comment by pkra** [comment]
I've changed the role to group. I tired adding the aria-hidden hackery without luck.

To recap: Chrome+NVDA suddenly did not like role=math anymore; it would not read in exploration, however when exploring and tabbing away and back to the expression, it *would* read the correct activedescendant. It just didn't seem to pick up the change.

FF+NVDA would still work with role=math (as does master). But after all the role doesn't matter.

=> ready to merge.
